version: 2
jobs:
    build_macos:
        macos:
            xcode: "10.0.0"
        steps:
            - checkout
            - run: ./scripts/install
            - run: which convert
            - run: which pdflatex
            - run: sudo python3 -m pip install nox
            - run: nox
    build_ubuntu:
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: ./scripts/install
            - run: sudo python3 -m pip install nox
            - run: nox
workflows:
    version: 2
    build_all:
        jobs:
            - build_macos
            - build_ubuntu
