version: 2
jobs:
    build:
        macos:
            xcode: "10.0.0"
        steps:
            - checkout
            - run:
                name: hello-world-test
                command: echo "hello, world!"
