#!/bin/bash
#
# Make sure that ImageMagick's `convert` command is allowed to read PDF
# files.
#
# NOTE: This is potentially a security risk, since PDF files can execute
#       arbitrary code, so make sure you only `convert` PDF files that
#       you trust!

set -euo pipefail

UPDATED_POLICY='  <policy domain="coder" rights="read" pattern="PDF" />'
POLICY_FILE=/etc/ImageMagick-6/policy.xml

set -x

grep -q "$UPDATED_POLICY" "$POLICY_FILE" \
    || sudo sed -i \
        "\$ i\\$UPDATED_POLICY" \
        "$POLICY_FILE"
