#!/bin/bash

set -eo pipefail

fail() {
    echo "$@" >&2
    exit 1
}


install_for_macos() {
    echo MacOS detected, installing via brew ... >&2
    brew update
    HOMEBREW_NO_AUTO_UPDATE=1 brew link --overwrite python3
    # These can have transient errors ...
    HOMEBREW_NO_AUTO_UPDATE=1 brew install imagemagick || true
    HOMEBREW_NO_AUTO_UPDATE=1 brew cask install basictex || true
    export PATH="$PATH:/Library/TeX/texbin"
    sudo tlmgr update --self
    sudo tlmgr install standalone varwidth
}


install_for_linux() {
    if which apt-get &> /dev/null; then
        echo Debian/Ubuntu detected, installing via apt-get ... >&2
        sudo apt-get update
        sudo apt-get install -y imagemagick texlive-latex-extra
        ./scripts/enable-imagemagick-permissions
    else
        fail "No known package manager for $OSTYPE \($(uname -a)\), quitting"
    fi
}


case "$OSTYPE" in
    darwin*) install_for_macos ;;
    linux-gnu) install_for_linux ;;
    *) fail "Unknown OSTYPE: $OSTYPE" ;;
esac

echo Installation successful >&2
