#!/bin/bash

set -euo pipefail

fail() {
    echo "$@" >&2
    exit 1
}


install_for_macos() {
    echo MacOS detected
    exit 2
}


install_for_linux() {
    echo Linux detected
    exit 3
}


case "$OSTYPE" in
    darwin) install_for_macos ;;
    linux-gnu) install_for_linux ;;
    *) fail "Unknown OSTYPE: $OSTYPE" ;;
esac
