#!/bin/bash

set -euo pipefail

fail() {
    echo "$@" >&2
    exit 1
}


install_for_macos() {
    echo MacOS detected
    exit 2
}


install_for_linux() {
    if which apt-get &> /dev/null; then
        echo Debian/Ubuntu detected, installing via apt-get ... >&2
        sudo apt-get update
        sudo apt-get install -y imagemagick texlive-latex-extra
    else
        fail "No known package manager for $OSTYPE \($(uname -a)\), quitting"
    fi
}


case "$OSTYPE" in
    darwin*) install_for_macos ;;
    linux-gnu) install_for_linux ;;
    *) fail "Unknown OSTYPE: $OSTYPE" ;;
esac
